export default [
  {
    id: 942676,
    access_kind: -1,
    name: "Web-дизайн в примерах и задачах",
    author: "Евсеев Д.А., Трофимов В.В.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942676.jpg",
    pages: 263,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942666,
    access_kind: -1,
    name: "Английский язык в сфере строительства = English for Building Engineering",
    author: "Гарагуля С.И.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942666.jpg",
    pages: 365,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942675,
    access_kind: -1,
    name: "Бухгалтерская (финансовая) отчетность государственных и муниципальных учреждений",
    author: "Качкова О.Е., Кришталева Т.И.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942675.jpg",
    pages: 371,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942677,
    access_kind: -1,
    name: "Бухгалтерская финансовая отчетность: задания для практических занятий",
    author: "Гришкина С.Н., Сиднева В.П.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942677.jpg",
    pages: 189,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942669,
    access_kind: -1,
    name: "Государственная и муниципальная социальная политика. Курс лекций",
    author: "Волгин Н.А., под ред.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942669.jpg",
    pages: 493,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942663,
    access_kind: -1,
    name: "Государственно-частное партнерство и саморегулируемые организации в реализации функций государства (вопросы теории и практики)",
    author: "Губанов И.А., Салин П.Б., Комаров С.А., под ред.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942663.jpg",
    pages: 336,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942138,
    access_kind: -1,
    name: "Гражданский процесс",
    author: "Кайль Я.Я.",
    pub_name: "Юстиция",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942138.jpg",
    pages: 352,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942473,
    access_kind: -1,
    name: "Гражданское право",
    author: "Вронская М.В.",
    pub_name: "Юстиция",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942473.jpg",
    pages: 407,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942674,
    access_kind: -1,
    name: "Гражданское процессуальное право для сотрудников органов внутренних дел",
    author: "Гриднева О.В.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942674.jpg",
    pages: 161,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942707,
    access_kind: -1,
    name: "Документационное обеспечение управления",
    author: "Вармунд В.В.",
    pub_name: "Юстиция",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942707.jpg",
    pages: 271,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942722,
    access_kind: -1,
    name: "Инновационные методы эффективного развития бизнеса",
    author: "Подлесных В.И.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942722.jpg",
    pages: 269,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942661,
    access_kind: -1,
    name: "История робототехнических систем и комплексов",
    author:
      "Бабанов Н.Ю., Макаров В.С., Бушуева М.С., Кабалдин Ю.С., Колотилин В.Е., Куркин А.А., Папунин А.В., Тумасов А.В., Беляков В.В., под ред.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942661.jpg",
    pages: 541,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942472,
    access_kind: -1,
    name: "Криминалистика",
    author: "Крюкова Н.И., Косолапова Н.В.",
    pub_name: "Юстиция",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942472.jpg",
    pages: 255,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942668,
    access_kind: -1,
    name: "Мастер по ремонту и обслуживанию автомобилей: Ремонт двигателей. Основы профессиональной деятельности",
    author: "Ткачева Г.В., Келеменев Н.В., Дмитриенко С.А.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942668.jpg",
    pages: 157,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942693,
    access_kind: -1,
    name: "Международная безопасность: правовые и социологические аспекты",
    author: "Иншаков С.М.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942693.jpg",
    pages: 175,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942713,
    access_kind: -1,
    name: "Международный коммерческий арбитраж",
    author: "Инамова Е.А.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942713.jpg",
    pages: 77,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942672,
    access_kind: -1,
    name: "Налоговые расчеты в бухгалтерском учете. Практикум",
    author: "Вахрушина М.А., Турганова Л.В.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942672.jpg",
    pages: 287,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942699,
    access_kind: -1,
    name: "Народная художественная культура. Практикум",
    author: "Кондратьева Н.Ю.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942699.jpg",
    pages: 65,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942658,
    access_kind: -1,
    name: "Органическая химия (с практикумом)",
    author: "Саенко О.Е.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942658.jpg",
    pages: 177,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942659,
    access_kind: -1,
    name: "Основы косметологии",
    author: "Бонапартова А.В.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942659.jpg",
    pages: 190,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942670,
    access_kind: -1,
    name: "Оценка и реструктуризация кредитно-финансовых институтов+ еПриложение",
    author: "Ордов К.В., Помулев А.А.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942670.jpg",
    pages: 239,
    have_attache: 1,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942664,
    access_kind: -1,
    name: "Правовое сознание и психология терроризма",
    author: "Безносов Д.С., Почебут Л.Г.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942664.jpg",
    pages: 226,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942712,
    access_kind: -1,
    name: "Профилактика коррупционного поведения в молодежной среде",
    author:
      "Мартыненко А.В., Милешина Н.А., Еремина С.С., Куприянов А.Ю., Царева Е.В., Потапова Л.А., под общ. ред.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942712.jpg",
    pages: 227,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942724,
    access_kind: -1,
    name: "Психологическая диагностика",
    author: "Донцов Д.А.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942724.jpg",
    pages: 291,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942548,
    access_kind: -1,
    name: "Римское право",
    author: "Рыбак С.В.",
    pub_name: "Юстиция",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942548.jpg",
    pages: 283,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942695,
    access_kind: -1,
    name: "Современное торговое дело",
    author: "Рогалева Н.Л.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942695.jpg",
    pages: 138,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942665,
    access_kind: -1,
    name: "Социальная работа. Подготовка к демонстрационному экзамену",
    author: "Шимановская Я.В.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942665.jpg",
    pages: 127,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942726,
    access_kind: -1,
    name: "Справочник по высшей математике",
    author: "Бутырин В.И.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942726.jpg",
    pages: 193,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942723,
    access_kind: -1,
    name: "Технический английский язык для специалистов в сфере IT-технологий",
    author: "Смирнова Е.В., Браженец К.С., Сидоркина Л.С., Киреева И.А.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942723.jpg",
    pages: 110,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942471,
    access_kind: -1,
    name: "Уголовный процесс",
    author: "Жариков Ю.С.",
    pub_name: "Юстиция",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942471.jpg",
    pages: 245,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942673,
    access_kind: -1,
    name: "Управление проектами в области информационных технологий",
    author:
      "Трифонов И.В., Трифонова Н.Н., Череповская Н.А., Корнеева И.В., Лукьянова А.В., под ред.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942673.jpg",
    pages: 235,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942696,
    access_kind: -1,
    name: "Физическая культура. Практикум",
    author: "Киреева Е.А.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942696.jpg",
    pages: 104,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942474,
    access_kind: -1,
    name: "Философия права",
    author: "Надвикова В.В., Шкатулла В.И.",
    pub_name: "Юстиция",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942474.jpg",
    pages: 292,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942671,
    access_kind: -1,
    name: "Финансы предприятий агропромышленного комплекса",
    author: "Наминова К.А., Бабошкина П.А.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942671.jpg",
    pages: 156,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942660,
    access_kind: -1,
    name: "Функциональное программирование",
    author: "Гордиенко А.П.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942660.jpg",
    pages: 277,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942662,
    access_kind: -1,
    name: "Экономика кадастровой деятельности",
    author: "Забаева М.Н.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942662.jpg",
    pages: 375,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942751,
    access_kind: -1,
    name: "Юридическая психология",
    author: "Васильев В.Л.",
    pub_name: "Юстиция",
    bbk_name: "",
    year: "2022",
    cover: "/external/books_new_mini/news/942751.jpg",
    pages: 604,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942651,
    access_kind: -1,
    name: "Бюджетные учреждения: планирование, учет, анализ и контроль",
    author:
      "Бахтурина Ю.И., Бехтерева И.С., Бобрышев А.Н., Васильева К.Н., Головин С.В., Ельчанинова О.В., Коробейникова Л.С., Костюкова Е.И., Кривошеев А.В.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942651.jpg",
    pages: 803,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942031,
    access_kind: -1,
    name: "Жилищное право",
    author: "Ручкина Г.Ф.",
    pub_name: "Юстиция",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942031.jpg",
    pages: 370,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 941911,
    access_kind: -1,
    name: "Законность как принцип уголовной ответственности",
    author: "Жариков Ю.С.",
    pub_name: "Юстиция",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/941911.jpg",
    pages: 260,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942653,
    access_kind: -1,
    name: "Китай на мировом рынке нефти и рынках природного газа",
    author: "Жуков С.В., Копытин И.А.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942653.jpg",
    pages: 36,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942656,
    access_kind: -1,
    name: "Психология здоровья",
    author: "Карнышев А.Д.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942656.jpg",
    pages: 294,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942650,
    access_kind: -1,
    name: "Риск-ориентированный подход к модернизации корпоративного управления",
    author: "Яковлев В.М.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942650.jpg",
    pages: 142,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942655,
    access_kind: -1,
    name: "Руководство пользователя по компьютерным программам КОРАЛЛ",
    author: "Лукьянов П.Б., Лукьянов Б.В.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942655.jpg",
    pages: 345,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942654,
    access_kind: -1,
    name: "Современные инновационные технологии и модели обучения в образовании",
    author: "Дадалко В.А.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942654.jpg",
    pages: 321,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942648,
    access_kind: -1,
    name: "Социологическое измерение качества жизни. Том 1",
    author:
      "Зубец А.Н., Новиков А.В., Оборский А.Ю., Селезнев П.С., Новиков П.А.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942648.jpg",
    pages: 303,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942647,
    access_kind: -1,
    name: "Социологическое измерение качества жизни. Том 2",
    author:
      "Зубец А.Н., Новиков А.В., Оборский А.Ю., Селезнев П.С., Новиков П.А.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942647.jpg",
    pages: 531,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942646,
    access_kind: -1,
    name: "Управление проектами в национальной и региональной экономике",
    author:
      "Безпалов В.В., Столярова А.Н., Панасенко С.В., Федюнин Д.В., Петросян Д.С., Мурзак Н.А., Автономова С.А., Боташева Л.С., Горин Д.С., Князева О.В.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942646.jpg",
    pages: 313,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942649,
    access_kind: -1,
    name: "Финансовый учет (продвинутый курс)",
    author: "Гришкина С.Н., Рожнова О.В., Щербинина Ю.В., Сиднева В.П.",
    pub_name: "КноРус",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942649.jpg",
    pages: 264,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
  {
    id: 942657,
    access_kind: -1,
    name: "Юридическая ответственность за земельные правонарушения",
    author: "Грачева О.С., Романова А.А.",
    pub_name: "Русайнс",
    bbk_name: "",
    year: "2021",
    cover: "/external/books_new_mini/news/942657.jpg",
    pages: 230,
    have_attache: 0,
    have_tests: 0,
    have_media: 0,
  },
];
